name: Upload to S3

on: 
  # main 브랜치에 push 및 merge할 때 실행
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Workflow를 매뉴얼하게 트리거할 수 있음
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      # checkout을 이용해 코드에 접근
      - name: Checkout files
        uses: actions/checkout@v3
      # aws-actions을 이용해 aws credentials 획득
      - name: AWS Configuration
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      # S3에 업로드
      - name: Sync to S3
        run: aws s3 sync ./dags s3://${{ secrets.AWS_S3_BUCKET }}/${{ secrets.AWS_DESTINATION_KEY }}/dags --delete
          
          
